### ISSUE TITLE
decouple.UndefinedValueError

### ISSUE THREAD

**Issue by momansoury** [Amir-Mohamad/shamim-interview#1]
درود وقت شما بخیر
من تازه جنگو رو شروع کردم وقتی میخواستم پروژه شما رو ران کنم به این مشکل خوردم ممنون میشم راهنمایی کنید

```

(venv) neo@linuxmint:~/Desktop/venv/shamim-interview$ python3 manage.py runserver
Traceback (most recent call last):
  File "/home/neo/Desktop/venv/shamim-interview/manage.py", line 22, in <module>
    main()
  File "/home/neo/Desktop/venv/shamim-interview/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/neo/Desktop/venv/shamim-interview/config/settings.py", line 24, in <module>
    SECRET_KEY = config('SECRET_KEY')
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neo/Desktop/venv/lib/python3.11/site-packages/decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
(venv) neo@linuxmint:~/Desktop/venv/shamim-interview$ 

```

**Comment by Amir-Mohamad** [comment]
سلام و درود
باید فایل .env بسازید کنار پروژه.

وقتی پروژه میخواد دیپلوی بشه روی سرور, مقادیری که مهم هستن مثل
SECREY_KEY نباید داخل settings.py نوشته شده باشن.
بجاش میان اونا رو داخل یه فایل به نام .env میزارن و اونجا مقادیر رو میدن.
برای ران کردن پروژه اگر هنوز متوجه نشدید میتونید طبق روش زیر عمل کنید :
یه فایل به نام .env بسازید.
مقادیر زیر روی توی .env بزارید.
SECRET_KEY=django-insecure-=_g2$3s$n&mi__%adlw7##2losz&a-6fk1lek1g7l!75y$n_v0
DEBUG=True
ALLOWED_HOSTS=127.0.0.1

و بعد پروژه رو ران کنید.
اگه علاقه مند به این موضوع هستید, مقاله زیر رو بخونید:
https://simpleisbetterthancomplex.com/2015/11/26/package-of-the-week-python-decouple.html
